name: bootcamp91
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  url_launcher: ^6.3.0
  loading_animation_widget: ^1.2.1
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/ic_welcome_image.png
    - assets/images/ic_login.png
    - assets/images/ic_register.png
    - assets/images/ic_login_screen.png   
    - assets/images/ic_card_bg.png 
    - assets/images/ic_create_cafe.png
    - assets/images/ic_cafe_managament.png
    - assets/images/ic_scaffold.png
    - assets/images/forgot_password.png
    - assets/images/ic_add_product.png
    - assets/images/avatars/avatar1.png
    - assets/images/avatars/avatar2.png
    - assets/images/avatars/avatar3.png
    - assets/images/avatars/avatar4.png
    - assets/images/avatars/avatar5.png
    - assets/images/avatars/avatar6.png
    - assets/images/avatars/avatar7.png
    - assets/images/avatars/avatar8.png
    - assets/images/avatars/avatar9.png
    - assets/images/avatars/avatar10.png
    - assets/images/avatars/avatar11.png
    - assets/images/avatars/avatar12.png
    - assets/images/ic_change_password.png 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/app_icon.png"
