// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmwp7xVwRuj2ANKZuL8pkstapmRKAEQX4',
    appId: '1:355226743945:web:7c70dfeba6d20794d18258',
    messagingSenderId: '355226743945',
    projectId: 'bootcamp91',
    authDomain: 'bootcamp91.firebaseapp.com',
    storageBucket: 'bootcamp91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPki7k6DspAa-AvRNNacC3CZiXSCpCPLk',
    appId: '1:355226743945:android:0181c1bd2dddcdbcd18258',
    messagingSenderId: '355226743945',
    projectId: 'bootcamp91',
    storageBucket: 'bootcamp91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAsiPVI3Ykg_NpSKR01KehumrCsMxEU3c',
    appId: '1:355226743945:ios:f8681e4a35cec5e9d18258',
    messagingSenderId: '355226743945',
    projectId: 'bootcamp91',
    storageBucket: 'bootcamp91.appspot.com',
    iosBundleId: 'com.example.bootcamp91',
  );
}
